### ISSUE TITLE
Fix unstable cache tests

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#955]
### Expected behavior
Application should cache response for `GET /api/delegates` endpoint. There is a test case for this functionality [here](https://github.com/LiskHQ/lisk/blob/development/test/functional/http/get/delegates.js#L26).

### Actual behavior
It sometimes does not cache response in Redis, or the Redis deletes the key. (And the test fails) 
`/api/delegates/` endpoint caches responses, but only sometimes.

### Steps to reproduce:
Run tests on Jenkins.

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk/issues/998

**Comment by nazarhussain** [comment]
@karmacoma I faced same issue in this build https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-1071/2/

**Comment by diego-G** [comment]
I've found another intermittent failure on `test/unit/modules/cache.js:249:22`. It was discovered after including the missing test unit file `helpers/cache.js`.

**Comment by karmacoma** [comment]
Just encountered the following on: https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-1197/2/

```
22:37:43   6 passing (4s)
22:37:43   1 failing
22:37:43 
22:37:43   1) cached endpoints
22:37:43        GET /blocks
22:37:43          should remove entry from cache on new block:
22:37:43      AssertionError: expected { Object (meta, data, ...) } to deeply equal null
```

**Comment by robladbrook** [comment]
I haven't had a chance to dive into this properly, but at first glance I'm high suspicious that by default the Lisk server instance and all the parallel functional tests are using the same Redis DB - executing various sets/gets/flushes etc so might be a race condition? 

I'll try and find some time to verify the theory.

**Comment by robladbrook** [comment]
I've been unable to reproduce the issue on my setup so my theory remains just a theory.

**Comment by karmacoma** [comment]
Closing issue, as since: https://github.com/LiskHQ/lisk/pull/1212 stability has been fixed.

**Comment by diego-G** [comment]
Again, a build has thrown an error related to the cache and not related to the issue itself. Here the output:
```
11:55:02   6 passing (10s)
11:55:02   1 failing
11:55:02 
11:55:02   1) cached endpoints
11:55:02        GET /transactions
11:55:02          cache transactions by the url and parameters when response is a success:
11:55:02      AssertionError: expected [ null, null, null ] to deep include { meta: { offset: 0, limit: 10, count: 1 },
11:55:02   data: 
11:55:02    [ { id: '9314232245035524467',
11:55:02        height: 1,
11:55:02        blockId: '6524861224470851795',
11:55:02        type: 3,
11:55:02        timestamp: 0,
11:55:02        senderPublicKey: 'c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f',
11:55:02        senderId: '16313739661670634666L',
11:55:02        recipientId: '16313739661670634666L',
11:55:02        recipientPublicKey: 'c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f',
11:55:02        amount: '0',
11:55:02        fee: '0',
11:55:02        signature: '9f9446b527e93f81d3fb8840b02fcd1454e2b6276d3c19bd724033a01d3121dd2edb0aff61d48fad29091e222249754e8ec541132032aefaeebc312796f69e08',
11:55:02        confirmations: 1,
11:55:02        asset: [Object],
11:55:02        multisignatures: [] } ],
11:55:02   links: {} }
11:55:02       at Promise.all.then.responses (test/functional/http/get/cache.js:72:32)
11:55:02       at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
11:55:02       at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
11:55:02       at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
11:55:02       at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
11:55:02       at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
11:55:02       at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
11:55:02       at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
11:55:02       at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
11:55:02       at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
11:55:02       at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
11:55:02       at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
11:55:02       at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
11:55:02       at node_modules/bluebird/js/release/nodeback.js:42:21
11:55:02       at Command.client.get [as callback] (modules/cache.js:9:2274)
11:55:02       at normal_reply (node_modules/redis/index.js:721:21)
11:55:02       at RedisClient.return_reply (node_modules/redis/index.js:819:9)
11:55:02       at JavascriptRedisParser.returnReply (node_modules/redis/index.js:192:18)
11:55:02       at JavascriptRedisParser.execute (node_modules/redis-parser/lib/parser.js:574:12)
11:55:02       at Socket.<anonymous> (node_modules/redis/index.js:274:27)
11:55:02       at readableAddChunk (_stream_readable.js:176:18)
11:55:02       at Socket.Readable.push (_stream_readable.js:134:10)
11:55:02       at TCP.onread (net.js:547:20)
```

**Comment by 4miners** [comment]
Issue is still present, https://jenkins.lisk.io/job/lisk-core/job/PR-2009/2/execution/node/202/log/
```
09:14:57 [0m  1) cached endpoints
09:14:57        GET /blocks
09:14:57          cache blocks by the url and parameters when response is a success:
09:14:57 [0m[31m     AssertionError: expected [ null, null, null ] to deep include { meta: { offset: 0, limit: 10 },
09:14:57   data: 
09:14:57    [ { id: '6524861224470851795',
09:14:57        version: 0,
09:14:57        timestamp: 0,
09:14:57        height: 1,
09:14:57        numberOfTransactions: 103,
09:14:57        totalAmount: '10000000000000000',
09:14:57        totalFee: '0',
09:14:57        reward: '0',
09:14:57        payloadLength: 19619,
09:14:57        payloadHash: '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
09:14:57        generatorPublicKey: 'c96dec3595ff6041c3bd28b76b8cf75dce8225173d1bd00241624ee89b50f2a8',
09:14:57        blockSignature: 'c81204bf67474827fd98584e7787084957f42ce8041e713843dd2bb352b73e81143f68bd74b06da8372c43f5e26406c4e7250bbd790396d85dea50d448d62606',
09:14:57        confirmations: 6,
09:14:57        totalForged: '0',
09:14:57        generatorAddress: '1085993630748340485L',
09:14:57        previousBlockId: '' } ],
09:14:57   links: {} }[0m[90m
09:14:57       at blocksEndpoint.makeRequest.then.then.responses (test/functional/http/get/cache.js:117:32)
09:14:57       at process._tickCallback (internal/process/next_tick.js:109:7)
09:14:57 [0m
09:14:57 
09:14:57 
09:14:58 Test failed: test/functional/http/get/cache.js
09:14:58 >> Exited with code: 1.
09:14:58 >> Error executing child process: Error: Process exited with code 1.
09:14:58 Warning: Task "exec:mocha:untagged:functional:get" failed. Use --force to continue.
```

**Comment by MaciejBaj** [comment]
https://jenkins.lisk.io/job/lisk-core/job/PR-2395/4/execution/node/214/log/
```
Test finished successfully: test/functional/http/get/blocks.js
11:38:32     [31m  1) should remove entry from cache on new block[0m
11:38:32 [0m    GET /delegates[0m
11:38:32     [32m  ✓[0m[90m should cache delegates when response is successful[0m[31m (110ms)[0m
11:38:32     [32m  ✓[0m[90m should not cache delegates when response is unsuccessful[0m
11:38:32 
11:38:32 
11:38:32 [92m [0m[32m 4 passing[0m[90m (11s)[0m
11:38:32 [31m  1 failing[0m
11:38:32 
11:38:32 [0m  1) cached endpoints
11:38:32        GET /blocks
11:38:32          should remove entry from cache on new block:
11:38:32 [0m[31m     AssertionError: expected { Object (meta, data, ...) } to deeply equal null[0m[90m
11:38:32       at blocksEndpoint.makeRequest.then.then.then.then.then.result (test/functional/http/get/cache.js:162:24)
11:38:32       at Command.client.get [as callback] (modules/cache.js:9:2284)
11:38:32       at normal_reply (node_modules/redis/index.js:721:21)
11:38:32       at RedisClient.return_reply (node_modules/redis/index.js:819:9)
11:38:32       at JavascriptRedisParser.returnReply (node_modules/redis/index.js:192:18)
11:38:32       at JavascriptRedisParser.execute (node_modules/redis-parser/lib/parser.js:574:12)
11:38:32       at Socket.<anonymous> (node_modules/redis/index.js:274:27)
11:38:32       at addChunk (_stream_readable.js:263:12)
11:38:32       at readableAddChunk (_stream_readable.js:250:11)
11:38:32       at Socket.Readable.push (_stream_readable.js:208:10)
11:38:32       at TCP.onread (net.js:601:20)
11:38:32   From previous event:
11:38:32       at Context.it (test/functional/http/get/cache.js:161:6)
11:38:32       at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:42:16)
11:38:32 [0m
11:38:32 
11:38:32
